target 'WYAMaterial' do

pod 'AFNetworking','~>3.2.1'
pod 'Masonry','~>1.1.0'
pod 'SDWebImage','~>4.4.1'
pod 'MBProgressHUD','~>1.1.0'
pod 'FMDB','~>2.7.2'
pod 'MJRefresh','~>3.1.15.3'
pod 'IQKeyboardManager','~>6.0.4'

pod 'YYModel','~>1.0.4'
pod 'Bugly','~>2.5.0'
pod 'WYAKit','~>0.1.0'
end
